# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170601_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='work_company',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='\u6240\u5c5e\u5927\u5b66'),
        ),
    ]
