# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-18 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170611_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseOrg',
            new_name='Org',
        ),
    ]
