# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170531_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorate',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '\u8bfe\u7a0b'), (2, '\u5927\u5b66'), (3, '\u8bb2\u5e08')], verbose_name='\u6536\u85cf\u7c7b\u578b'),
        ),
    ]
