# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20170602_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavorate',
            new_name='UserFavorite',
        ),
    ]
