# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-22 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_userask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAsk',
        ),
    ]
