# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-11 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u9996\u9875\u8f6e\u64ad'),
        ),
    ]
